spring.application.name=campusclash


# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/campus_clash
spring.datasource.username=root
spring.datasource.password=05@SamSantosh

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true