services:
  - type: web
    name: ves-campus-clash-backend
    env: java
    plan: free
    rootDir: backend/campusclash
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar